# Change these first
owner: cozv # Your GitHub organization or username, where this repository lives
repo: cozv.github.io # The name of this repository

sites:
  - name: COZV
    url: https://www.cozv.com
    icon: https://www.cozv.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/48952628
  name: cozvUptime
  introTitle: "The official uptime monitor and status page for [COZV.com](https://cozv.com)"
  introMessage: using GitHub Action to fetch **real-time** data from [COZV.com](https://cozv.com).
  favicon: https://cozv.com/
  navbar:
    - title: Status
      href: /
    - title: COZV.com
      href: https://www.cozv.com/safari-pinned-tab.svg