# Change these first
owner: cozv # Your GitHub organization or username, where this repository lives
repo: cozv.github.io # The name of this repository

sites:
  - name: cozvUptime
    url: https://www.cozv.com
    icon: https://www.cozv.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/48952628
  name: cozvUptime
  introTitle: "Uptime monitor and status page for [COZV.com](https://cozv.com)"
  introMessage: using GitHub Action to fetch **real-time** data from COZV.com.
  favicon: https://cozv.com/
  themeUrl: https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css
  links:
    - rel: stylesheet
      href: https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css
  css: "body { font-family: -apple-system, BlinkMacSystemFont, system-ui, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
  navbar:
    - title: Status
      href: /
    - title: COZV.com
      href: https://www.cozv.com/safari-pinned-tab.svg